"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = ['FONDO-3.png','FONDO-MENU.png', 'FONDOCLIENTES.png', 'FONDOSEARCH.png']
OPTIONS = {'iconfile':'icon.icns',
    'plist': {'CFBundleShortVersionString':'0.1.0',} }

setup(
    app=APP,
    name ='CrisBoutique',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
